Repository JNU-econovation/DUNDUN, pull requests merged in 2023-07, with the labels that each got.

#13 [Init] 파이어베이스 사용설정
  app/build.gradle
  build.gradle
Labels: feature, BE

#12 [Feature] 바텀 네비게이션 바
  app/build.gradle
  app/src/main/java/com/project981/dundun/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/HomeFragment.kt
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/MapFragment.kt
  app/src/main/java/com/project981/dundun/SearchFragment.kt
  app/src/main/java/com/project981/dundun/SettingFragment.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/menu/bottom_menu.xml
  app/src/main/res/navigation/my_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#15 [Feature] 뷰바인딩 및 패키지 변경
  app/build.gradle
  app/src/main/java/com/project981/dundun/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/HomeFragment.kt
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/MapFragment.kt
  app/src/main/java/com/project981/dundun/SearchFragment.kt
  app/src/main/java/com/project981/dundun/SettingFragment.kt
  app/src/main/java/com/project981/dundun/view/calendar/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/view/home/HomeFragment.kt
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/search/SearchFragment.kt
  app/src/main/java/com/project981/dundun/view/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/navigation/my_nav.xml
Labels: feature, FE, refactor

#17 [Feature] DTO 생성
  app/src/main/java/com/project981/dundun/model/dto/CalendarDetailDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/CalendarDotDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/FollowListDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/MapDetailDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/MapItemDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/MarkerDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/NoticeChangeDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/NoticeDisplayDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/ProfileTopDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/firebase/ArtistDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/firebase/NoticeDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/firebase/UserDTO.kt
Labels: feature, BE

#16 [Feature] 카카오맵 api 연동
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/search/SearchFragment.kt
  app/src/main/java/com/project981/dundun/view/setting/SettingFragment.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/layout/fragment_map.xml
Labels: feature, FE

#21 [Feature] 텍스트 스타일 생성
  app/src/main/res/values/styles.xml
Labels: feature, FE

#23 [Feature] sign in
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project981/dundun/SignActivity.kt
  app/src/main/java/com/project981/dundun/domain/UserSignInUseCase.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/signin/SignInFragment.kt
  app/src/main/java/com/project981/dundun/view/signin/SigninViewModel.kt
  app/src/main/res/drawable/signin_textfield_shape.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/navigation/sign_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature, FE, BE

#24 [Fix] remove appbar
  app/src/main/java/com/project981/dundun/MainActivity.kt
Labels: bug, fix

#26 [Feature] 회원가입과 로그인 연결
  app/src/main/java/com/project981/dundun/SignActivity.kt
  app/src/main/java/com/project981/dundun/domain/UserSignUpUseCase.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/signselect/SignSelectFragment.kt
  app/src/main/java/com/project981/dundun/view/signselect/TypeSelectFragment.kt
  app/src/main/java/com/project981/dundun/view/signselect/TypeViewModel.kt
  app/src/main/java/com/project981/dundun/view/signup/SignUpFragment.kt
  app/src/main/java/com/project981/dundun/view/signup/SignupViewModel.kt
  app/src/main/res/drawable/dundun_logo.xml
  app/src/main/res/drawable/sign_select_shape.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/fragment_sign_select.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/layout/fragment_type_select.xml
  app/src/main/res/navigation/sign_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, FE, BE

#32 [Feature] calendar view
  app/src/main/java/com/project981/dundun/domain/GetEventListByMonthAndYearUseCase.kt
  app/src/main/java/com/project981/dundun/model/dto/BottomDetailDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/CalendarDetailDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/CalendarDotDTO.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/calendar/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/view/calendar/CalendarViewModel.kt
  app/src/main/java/com/project981/dundun/view/calendar/CustomCalendar.kt
  app/src/main/java/com/project981/dundun/view/calendar/CustomCalendarItem.kt
  app/src/main/java/com/project981/dundun/view/map/BottomRecyclerAdapter.kt
  app/src/main/res/drawable/baseline_arrow_drop_down_24.xml
  app/src/main/res/layout/bottom_list_item.xml
  app/src/main/res/layout/calendar_monthpicker.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values/colors.xml
Labels: feature, FE

#29 [Feature] 프로필 페이지, 게시글 작성 페이지 레이아웃
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_my_profile.xml
  app/src/main/res/layout/add_notice_write.xml
  app/src/main/res/values/dimens.xml
Labels: feature, FE

#34 [Feature] map bottom sheet
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/res/drawable/ic_list.xml
  app/src/main/res/layout/bottomsheet_list.xml
  app/src/main/res/layout/bottomsheet_map.xml
  app/src/main/res/layout/fragment_map.xml
Labels: feature, FE

#36 [Feature] artist page multiview
  app/build.gradle
  app/src/main/java/com/project981/dundun/view/artist/MyPageFragment.kt
  app/src/main/java/com/project981/dundun/view/artist/PageAdapter.kt
  app/src/main/java/com/project981/dundun/view/artist/WriteNoticeFragment.kt
  app/src/main/java/com/project981/dundun/view/home/HomeFragment.kt
  app/src/main/java/com/project981/dundun/view/home/NoticeAdapter.kt
  app/src/main/res/layout/add_my_profile.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_noticewrite.xml
  app/src/main/res/layout/map_test.xml
  app/src/main/res/navigation/my_nav.xml
Labels: feature, FE

#37 [Feature] marker and clustering
  app/build.gradle
  app/src/main/java/com/project981/dundun/domain/GetMarkerListByDistanceAndGeoUseCase.kt
  app/src/main/java/com/project981/dundun/model/dto/BottomDetailDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/MapItemDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/MarkerDTO.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/map/Cluster.kt
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/map/MapViewModel.kt
  app/src/main/res/drawable/marker_img_1.png
  app/src/main/res/drawable/marker_img_10.png
  app/src/main/res/drawable/marker_img_2.png
  app/src/main/res/drawable/marker_img_3.png
  app/src/main/res/drawable/marker_img_4.png
  app/src/main/res/drawable/marker_img_5.png
  app/src/main/res/drawable/marker_img_6.png
  app/src/main/res/drawable/marker_img_7.png
  app/src/main/res/drawable/marker_img_8.png
  app/src/main/res/drawable/marker_img_9.png
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/navigation/my_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, FE, BE

#41 [Feature] Search 페이지에서 아티스트 이름 검색 기능 구현
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/search/SearchFragment.kt
  app/src/main/java/com/project981/dundun/view/search/SearchViewModel.kt
  app/src/main/java/com/project981/dundun/view/search/UserAdapter.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/layout/add_notice_write.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search.xml
Labels: feature, FE

#43 Feature/artist page
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/MainViewModel.kt
  app/src/main/java/com/project981/dundun/view/artist/MyPageFragment.kt
  app/src/main/java/com/project981/dundun/view/artist/PageAdapter.kt
  app/src/main/java/com/project981/dundun/view/artist/ProfileViewModel.kt
  app/src/main/res/layout/add_my_profile.xml
  app/src/main/res/layout/notice_item.xml
  app/src/main/res/navigation/my_nav.xml
  app/src/main/res/values/colors.xml
Labels: feature, FE

#44 Feature/profile connect
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/model/dto/NoticeDisplayDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/ProfileTopDTO.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/MainViewModel.kt
  app/src/main/java/com/project981/dundun/view/artist/MyPageFragment.kt
  app/src/main/java/com/project981/dundun/view/calendar/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/view/home/HomeFragment.kt
  app/src/main/java/com/project981/dundun/view/home/NoticeAdapter.kt
  app/src/main/java/com/project981/dundun/view/map/BottomRecyclerAdapter.kt
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/search/SearchFragment.kt
  app/src/main/java/com/project981/dundun/view/search/UserAdapter.kt
  app/src/main/res/drawable/my_follow_shape_f.xml
  app/src/main/res/drawable/my_follow_shape_t.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/notice_item.xml
  app/src/main/res/navigation/my_nav.xml
Labels: feature, FE

#46 [Feature] write notice page
  app/src/main/java/com/project981/dundun/view/artist/NoticeViewModel.kt
  app/src/main/java/com/project981/dundun/view/artist/WriteNoticeFragment.kt
  app/src/main/res/layout/add_notice_write.xml
  app/src/main/res/layout/fragment_noticewrite.xml
Labels: feature, FE

#48 [Feature] 상단 툴바 적용, 게시글 작성 페이지 switch 색상 변경
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/view/artist/PageAdapter.kt
  app/src/main/java/com/project981/dundun/view/home/NoticeAdapter.kt
  app/src/main/res/color/switch_background_selector.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_noticewrite.xml
  app/src/main/res/layout/notice_item.xml
  app/src/main/res/values/colors.xml
Labels: feature, fix, FE

#49 [Feature] 프로필 편집 dialog 레이아웃 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project981/dundun/view/artist/MyPageFragment.kt
  app/src/main/res/layout/edit_my_profile.xml
Labels: feature, FE

#50 [Feature] create and edit notice
  app/src/main/java/com/project981/dundun/domain/DeleteNoticeUseCase.kt
  app/src/main/java/com/project981/dundun/domain/GetNoticeUseCase.kt
  app/src/main/java/com/project981/dundun/model/dto/NoticeGetDTO.kt
  app/src/main/java/com/project981/dundun/model/dto/firebase/ArtistDTO.kt
  app/src/main/java/com/project981/dundun/model/repository/MainRepository.kt
  app/src/main/java/com/project981/dundun/view/artist/PageAdapter.kt
  app/src/main/java/com/project981/dundun/view/artist/WriteNoticeFragment.kt
  app/src/main/java/com/project981/dundun/view/artist/WriteNoticeViewModel.kt
  app/src/main/java/com/project981/dundun/view/home/HomeFragment.kt
  app/src/main/java/com/project981/dundun/view/home/NoticeAdapter.kt
  app/src/main/java/com/project981/dundun/view/map/BottomRecyclerAdapter.kt
  app/src/main/res/drawable/ic_cross.xml
  app/src/main/res/layout/add_notice_write.xml
  app/src/main/res/layout/dialog_map.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_noticewrite.xml
  app/src/main/res/layout/notice_item.xml
Labels: feature, FE, BE

#51 [Fix] change color and icon size of GPS button
  app/src/main/res/layout/fragment_map.xml
Labels: fix, FE

#53 [Feature] setting fragment design
  app/src/main/java/com/project981/dundun/MainActivity.kt
  app/src/main/java/com/project981/dundun/view/MainViewModel.kt
  app/src/main/java/com/project981/dundun/view/artist/MyPageFragment.kt
  app/src/main/java/com/project981/dundun/view/artist/WriteNoticeFragment.kt
  app/src/main/java/com/project981/dundun/view/calendar/CalendarFragment.kt
  app/src/main/java/com/project981/dundun/view/home/HomeFragment.kt
  app/src/main/java/com/project981/dundun/view/map/MapFragment.kt
  app/src/main/java/com/project981/dundun/view/setting/SettingFragment.kt
  app/src/main/res/drawable/ic_dot.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: feature, FE
